import { fileURLToPath } from 'node:url';
import path from 'node:path';

/** Repository root, resolved from this file's location. */
export const REPO_ROOT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
  '..',
);

export const SKILLS_DIR = path.join(REPO_ROOT, '.claude', 'skills');
export const AGENTS_DIR = path.join(REPO_ROOT, '.claude', 'agents');
export const HOOKS_DIR = path.join(REPO_ROOT, '.claude', 'hooks');
export const AGENTS_MD = path.join(REPO_ROOT, 'AGENTS.md');

export const GH_PROMPTS_DIR = path.join(REPO_ROOT, '.github', 'prompts');
export const GH_AGENTS_DIR = path.join(REPO_ROOT, '.github', 'agents');
export const GH_INSTRUCTIONS = path.join(
  REPO_ROOT,
  '.github',
  'copilot-instructions.md',
);

/** Marker identifying generated files. Also used to detect strays. */
export const GENERATED_MARKER = 'GENERATED by scripts/sync.mjs';

/**
 * Header stamped onto every generated file.
 * @param {string} source Repo-relative path of the file this was generated from.
 */
export function generatedHeader(source) {
  return `<!-- ${GENERATED_MARKER} — do not edit. Edit ${source} instead. -->\n`;
}

/** Repo-relative POSIX path, for stable output across platforms. */
export function rel(absolutePath) {
  return path.relative(REPO_ROOT, absolutePath).split(path.sep).join('/');
}
